[build]
  functions = "functions"
[functions]
  node_bundler = "esbuild"
[[redirects]]
    from = "/"
    to = "/.netlify/functions/index"
    status = 200
[[redirects]]
    from = "/api/"
    to = "/.netlify/functions/index"
    status = 200
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200